files:
  - source: /**/docs/**/*.md
    ignore:
      - /**/docs/%two_letters_code%/
    translation: /**/docs/%two_letters_code%/**/%original_file_name%
  - source: /**/docs/.vitepress/i18n/strings/en.json
    ignore:
      - /**/docs/.vitepress/i18n/strings/%two_letters_code%
    translation: /**/docs/.vitepress/i18n/strings/%two_letters_code%.json
